import psycopg2, os
env = open('/var/www/inventory/ResortApp/.env').read()
db_url = [l for l in env.splitlines() if l.startswith('DATABASE_URL=')][0].split('=',1)[1].strip()
conn = psycopg2.connect(db_url)
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM account_groups")
print("Groups:", cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM account_ledgers")
print("Ledgers:", cur.fetchone()[0])
cur.execute("SELECT id, name, account_type FROM account_groups LIMIT 10")
rows = cur.fetchall()
print("Sample groups:", rows)
conn.close()
